### ISSUE TITLE
Syntax error in Queries/Advanced Queries/Tutorial Example 9 

### ISSUE THREAD

**Issue by AvijeetPrasad** [mschmidtkorth/logseq-msk-docs#6]
Hi,
I was trying to work with the examples given in your wonderful [Advanced Queries tutorial]((https://mschmidtkorth.github.io/logseq-msk-docs/#/page/612d1a8c-62db-414d-ad84-326d9473c91f).) I noticed that example 9 is giving a syntax error when pasted. I am pasting that part below for your quick reference. Can you have a look?

Thanks and regards
Avijeet

```
#+BEGIN_QUERY
{:title "⚠️ OVERDUE"
	:query [:find (pull ?block [*])
in $ ?start ?today
where
?block :block/marker ?marker]
	  
or
[?block :block/scheduled ?d]
[?block :block/deadline ?d])
	  
(>= ?d ?start)]
(<   ?d ?today)]
	  
(contains? #{"NOW" "LATER" "TODO" "DOING" "WAITING"} ?marker)]]
:inputs [:180d :today]
:result-transform  (fn [result]
				(sort-by  (fn [d]
				(get d :block/deadline) ) result ))
:collapsed? false}
#+END_QUERY
```

**Comment by mschmidtkorth** [comment]
Thanks @AvijeetPrasad! Looks like the colons got lost. This is fixed now.

**Comment by AvijeetPrasad** [comment]
Hi @mschmidtkorth, Thanks for the update. I was wondering if this query can be updated to include the overdue tasks from the journal pages as well? I think that would make this even more useful. If possible can you please add an example for that in the tutorial page as well? Thanks!
