### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by Nachasic** [mschmidtkorth/logseq-msk-docs#8]
I am working on an learning resource on using Logseq for PKM. I'm planning to release it eventually under an CC BY-SA license, and I wish I could incorporate some of your work in the graph. However, I cannot do so right now because due to the absence of a license file I should think this work proprietary by default.

Would you consider attaching some sort of a permissive license?

**Comment by mschmidtkorth** [comment]
Hi Alex - good point, I'm going to add one some time later. Please consider
it to be under GNU GPLv3 <https://choosealicense.com/licenses/gpl-3.0/> for
the time being. Let me know if that works for you.

**Comment by mschmidtkorth** [comment]
Added license.
