### ISSUE TITLE
Can you share your theme

### ISSUE THREAD

**Issue by Iamlovingit** [mschmidtkorth/logseq-msk-docs#9]
This is a great work. Your theme is very cool. Can you share it?
![image](https://github.com/mschmidtkorth/logseq-msk-docs/assets/38182824/700ae232-4c3b-472b-968c-9897825e0617)

**Comment by mischmiko** [comment]
Hey @Iamlovingit, of course – you can find it here: https://github.com/mschmidtkorth/logseq-msk-enhanced

**Comment by mschmidtkorth** [comment]
Hey @Iamlovingit, thanks for the kind words. Of course – you can find it here: https://github.com/mschmidtkorth/logseq-msk-enhanced
